### ISSUE TITLE
evalDsl action throws an unnecessary message

### ISSUE THREAD

**Issue by gmaxey** [zvercodebender/cdrodsl-action#1]
When run from a workflow, evalDsl throws the error:

`open /root/.cdro-cli.json: no such file or directory`

**Comment by zvercodebender** [comment]
1. Were you also getting a `ERROR: 401 Unauthorized`?
2. Were you trying to use a TOKEN?
3. What were you expecting?

**Comment by zvercodebender** [comment]
I think this is really a `cdro-cli` issue (https://github.com/zvercodebender/cdro-cli/issues/1)

**Comment by zvercodebender** [comment]
This is resolved in 0.7 of the `cdro-cli`
